update faillog - ubuntu5/un_fsic.log - after replace from sw_caravel.v.patch to sw_caravel.v then make user_proj_example fail in below
[STEP 14]
[INFO]: Running Detailed Placement (log: ../ADATA2T/debug/fsic_1004_gl_issue/caravel_user_project/openlane/user_proj_example/runs/23_10_05_10_13/logs/routing/14-diode_legalization.log)...
[ERROR]: during executing openroad script /openlane/scripts/openroad/dpl.tcl
[ERROR]: Log: ../ADATA2T/debug/fsic_1004_gl_issue/caravel_user_project/openlane/user_proj_example/runs/23_10_05_10_13/logs/routing/14-diode_legalization.log
[ERROR]: Last 10 lines:
[INFO DPL-0035]  ANTENNA__12935__A
[INFO DPL-0035]  ANTENNA_input13_A
[INFO DPL-0035]  ANTENNA_input43_A
[INFO DPL-0035]  ANTENNA_input43_A
[INFO DPL-0035]  ANTENNA_input42_A
[INFO DPL-0035]  ANTENNA_input84_A
[INFO DPL-0035]  ANTENNA_input84_A
[ERROR DPL-0036] Detailed placement failed.
Error: dpl.tcl, 20 DPL-0036
child process exited abnormally

[ERROR]: Creating issue reproducible...