update fail log bash_auto/run_fsic.log - error in make -d verify-system_test111-gl
Invoking recipe from /ADATA2T/debug/fsic_1005_main/caravel_user_project/mgmt_core_wrapper/verilog/dv/make/sim.makefile:82 to update target `system_test111.vvp'.
iverilog -Ttyp -DFUNCTIONAL -DGL -DSIM -DUSE_POWER_PINS -DUNIT_DELAY=#1 \
        -g2012 \
        -f/ADATA2T/debug/fsic_1005_main/caravel_user_project/mgmt_core_wrapper/verilog/includes/includes.gl.caravel \
        -f/ADATA2T/debug/fsic_1005_main/caravel_user_project/verilog/includes/includes.gl.caravel_user_project -o system_test111.vvp system_test111_tb.v
Putting child 0x16afb70 (system_test111.vvp) PID 34 on the chain.
Live child 0x16afb70 (system_test111.vvp) PID 34
./fpga.v:101: error: Unknown module type: IO_SERDES
2 error(s) during elaboration.
*** These modules were missing:
        IO_SERDES referenced 1 times.
***
make: *** [system_test111.vvp] Error 2